requirements.txt: Add torchaudio==2.0.2 in to requirements.txt
fix error message

Installing collected packages: torch
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.1 requires torch==2.3.1, but you have torch 2.0.1 which is incompatible.

when use pip install -r requirements.txt